[package]
name = "lol_os"
version = "0.1.0"
authors = ["Christian Eckenrode <chriseckenrode@me.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
default-target = "x86_64-lol_os.json"

[dependencies]
bootloader = "0.4.0"
